name       : python-parsedatetime
version    : '2.4'
release    : 2
source     :
    - https://pypi.python.org/packages/e3/b3/02385db13f1f25f04ad7895f35e9fe3960a4b9d53112775a6f7d63f264b6/parsedatetime-2.4.tar.gz : 3d817c58fb9570d1eec1dd46fa9448cd644eeed4fb612684b02dfda3a79cb84b
license    : Apache-2.0
component  : programming.python
summary    : Parse human-readable date/time strings.
description: |
    Parse human-readable date/time strings.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-future
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

