name       : python-parsedatetime
version    : 2.4
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/parsedatetime/parsedatetime-2.4.tar.gz : 3d817c58fb9570d1eec1dd46fa9448cd644eeed4fb612684b02dfda3a79cb84b
license    : Apache-2.0
component  : programming.python
summary    : Parse human-readable date/time strings
description: |
    Python module that can parse human-readable date/time strings.
builddeps  :
    - pkgconfig(python3)
    - python-future
    - pytest-runner
rundeps    :
    - python-future
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
