name       : python-parsedatetime
version    : 2.3
release    : 1
source     :
    - https://github.com/bear/parsedatetime/archive/v2.3.tar.gz : eb99b2d82f9dace7875a0678b7a9928b2aa379b68f99b8ba6f850e7cd8dca0a4
license    : Apache-2.0
component  : programming.python
summary    : Parse human-readable date/time strings.
description: |
    Parse human-readable date/time strings.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
    - pytest-runner
rundeps    :
    - python-future
    - pytest-runner
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install